apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rest-ingress-630af869-856a-4261-9a9a-4066c9c15d85
  namespace: 3219e62e-f28c-4e9a-b62e-77aae69fb44b
  labels:
    app: rest-app-630af869-856a-4261-9a9a-4066c9c15d85
spec:
  ingressClassName: nginx
  rules:
    - host: app-l8qg6w.mo09zm.us-east-2.febe.k8s
      http:
        paths:
          - path: /febe-rest-630af869-856a-4261-9a9a-4066c9c15d85/
            pathType: Prefix
            backend:
              service:
                name: rest-service-630af869-856a-4261-9a9a-4066c9c15d85
                port:
                  number: 80
