apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-app-630af869-856a-4261-9a9a-4066c9c15d85
  namespace: 3219e62e-f28c-4e9a-b62e-77aae69fb44b
  labels:
    app: rest-app-630af869-856a-4261-9a9a-4066c9c15d85
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-app-630af869-856a-4261-9a9a-4066c9c15d85
  template:
    metadata:
      labels:
        app: rest-app-630af869-856a-4261-9a9a-4066c9c15d85
    spec:
      containers:
      - name: rest630af869-856a-4261-9a9a-4066c9c15d85
        image: ravi8881/3219e62e-f28c-4e9a-b62e-77aae69fb44b-70114ee3-7c51-40a6-af98-bd2ca53150ad-17cd568b-1349-4670-a8ae-53d47334febc-7d9588f5-18bc-42fe-8c24-367054f3da0c-rest:5.0.0
        ports:
        - containerPort: 8080
