apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-app-99c6f191-c106-4300-9ff2-15ab7314c964
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
  labels:
    app: rest-app-99c6f191-c106-4300-9ff2-15ab7314c964
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-app-99c6f191-c106-4300-9ff2-15ab7314c964
  template:
    metadata:
      labels:
        app: rest-app-99c6f191-c106-4300-9ff2-15ab7314c964
    spec:
      containers:
      - name: rest99c6f191-c106-4300-9ff2-15ab7314c964
        image: ravi8881/2e49f282-85d5-4866-af7d-8133a75e6769--bc5fa525-1f32-4c53-bf17-b98dd59ff12e-d9ae9c25-4bc5-4507-83f9-edf988812194-rest:0.0.1
        ports:
        - containerPort: 8080
