apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rest-ingress-50f89a6b-2a8c-451f-bddf-2d7efb75110e
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
  labels:
    app: rest-app-50f89a6b-2a8c-451f-bddf-2d7efb75110e
spec:
  ingressClassName: nginx
  rules:
    - host: tms-awj5np.ui1781.us-east-2.febe.kbs
      http:
        paths:
          - path: /febe-rest-50f89a6b-2a8c-451f-bddf-2d7efb75110e/
            pathType: Prefix
            backend:
              service:
                name: rest-service-50f89a6b-2a8c-451f-bddf-2d7efb75110e
                port:
                  number: 80
