apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-app-05a9a253-a873-43ca-8913-d317e491c165
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
  labels:
    app: rest-app-05a9a253-a873-43ca-8913-d317e491c165
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-app-05a9a253-a873-43ca-8913-d317e491c165
  template:
    metadata:
      labels:
        app: rest-app-05a9a253-a873-43ca-8913-d317e491c165
    spec:
      containers:
      - name: rest05a9a253-a873-43ca-8913-d317e491c165
        image: ravi8881/2e49f282-85d5-4866-af7d-8133a75e6769--bc5fa525-1f32-4c53-bf17-b98dd59ff12e-33314d28-2f4d-4613-bd40-2fd2bf1a89f5-rest:4.0.0
        ports:
        - containerPort: 8080
