apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rest-ingress-2f06784f-c6b6-4778-90a2-8fa5124eef88
  namespace: 3219e62e-f28c-4e9a-b62e-77aae69fb44b
  labels:
    app: rest-app-2f06784f-c6b6-4778-90a2-8fa5124eef88
spec:
  ingressClassName: nginx
  rules:
    - host: app-h8vt54.z2h9we.us-east-2.febe.k8s
      http:
        paths:
          - path: /febe-rest-2f06784f-c6b6-4778-90a2-8fa5124eef88/
            pathType: Prefix
            backend:
              service:
                name: rest-service-2f06784f-c6b6-4778-90a2-8fa5124eef88
                port:
                  number: 80
