apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rest-ingress-cf2c24a3-16d5-4ce0-9c22-7b5116205354
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
  labels:
    app: rest-app-cf2c24a3-16d5-4ce0-9c22-7b5116205354
spec:
  ingressClassName: nginx
  rules:
    - host: project-3-z0dqwh.wsa3gv.us-east-2.febe.kbs
      http:
        paths:
          - path: /febe-rest-cf2c24a3-16d5-4ce0-9c22-7b5116205354/
            pathType: Prefix
            backend:
              service:
                name: rest-service-cf2c24a3-16d5-4ce0-9c22-7b5116205354
                port:
                  number: 80
