apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-app-825c87fd-3f76-4865-bdf7-f4a989a45d6c
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
  labels:
    app: rest-app-825c87fd-3f76-4865-bdf7-f4a989a45d6c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-app-825c87fd-3f76-4865-bdf7-f4a989a45d6c
  template:
    metadata:
      labels:
        app: rest-app-825c87fd-3f76-4865-bdf7-f4a989a45d6c
    spec:
      containers:
      - name: rest825c87fd-3f76-4865-bdf7-f4a989a45d6c
        image: ravi8881/2e49f282-85d5-4866-af7d-8133a75e6769--bc5fa525-1f32-4c53-bf17-b98dd59ff12e-c0ab55d1-3bd3-4dbb-a1c8-a80818b7e521-rest:7.0.0
        ports:
        - containerPort: 8080
