apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rest-ingress-3d24da32-0af5-4bda-a27f-962a35c184ed
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
  labels:
    app: rest-app-3d24da32-0af5-4bda-a27f-962a35c184ed
spec:
  ingressClassName: nginx
  rules:
    - host: project-3-3u8bwo.1almrp.us-east-2.febe.kbs
      http:
        paths:
          - path: /febe-rest-3d24da32-0af5-4bda-a27f-962a35c184ed/
            pathType: Prefix
            backend:
              service:
                name: rest-service-3d24da32-0af5-4bda-a27f-962a35c184ed
                port:
                  number: 80
