apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rest-ingress-28fe4287-5ebc-4d88-849a-3cc27bd070d5
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
  labels:
    app: rest-app-28fe4287-5ebc-4d88-849a-3cc27bd070d5
spec:
  ingressClassName: nginx
  rules:
    - host: project-3-abmsig.okddz0.us-east-2.febe.kbs
      http:
        paths:
          - path: /febe-rest-28fe4287-5ebc-4d88-849a-3cc27bd070d5/
            pathType: Prefix
            backend:
              service:
                name: rest-service-28fe4287-5ebc-4d88-849a-3cc27bd070d5
                port:
                  number: 80
