apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rest-ingress-f8eee0fa-8d8b-4e19-8ee8-56864de7bbd8
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
  labels:
    app: rest-app-f8eee0fa-8d8b-4e19-8ee8-56864de7bbd8
spec:
  ingressClassName: nginx
  rules:
    - host: project-3-67aaze.e02m4g.us-east-2.febe.kbs
      http:
        paths:
          - path: /febe-rest-f8eee0fa-8d8b-4e19-8ee8-56864de7bbd8/
            pathType: Prefix
            backend:
              service:
                name: rest-service-f8eee0fa-8d8b-4e19-8ee8-56864de7bbd8
                port:
                  number: 80
