apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rest-ingress-a10db096-325c-49a2-9f34-d218b84fbb36
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
  labels:
    app: rest-app-a10db096-325c-49a2-9f34-d218b84fbb36
spec:
  ingressClassName: nginx
  rules:
    - host: project-3-fhosr6.9p67ia.us-east-2.febe.kbs
      http:
        paths:
          - path: /febe-rest-a10db096-325c-49a2-9f34-d218b84fbb36/
            pathType: Prefix
            backend:
              service:
                name: rest-service-a10db096-325c-49a2-9f34-d218b84fbb36
                port:
                  number: 80
