apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-app-0ffe9fe5-5bdb-4f50-ab78-018f01a3b1d3
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
  labels:
    app: rest-app-0ffe9fe5-5bdb-4f50-ab78-018f01a3b1d3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-app-0ffe9fe5-5bdb-4f50-ab78-018f01a3b1d3
  template:
    metadata:
      labels:
        app: rest-app-0ffe9fe5-5bdb-4f50-ab78-018f01a3b1d3
    spec:
      containers:
      - name: rest0ffe9fe5-5bdb-4f50-ab78-018f01a3b1d3
        image: ravi8881/2e49f282-85d5-4866-af7d-8133a75e6769--bc5fa525-1f32-4c53-bf17-b98dd59ff12e-c0ab55d1-3bd3-4dbb-a1c8-a80818b7e521-rest:5.0.0
        ports:
        - containerPort: 8080
