apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rest-ingress-f09b7e05-2e20-45d4-9407-7ac6d0cf59ce
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
  labels:
    app: rest-app-f09b7e05-2e20-45d4-9407-7ac6d0cf59ce
spec:
  ingressClassName: nginx
  rules:
    - host: project-3-ymxe7u.uwr7uw.us-east-2.febe.kbs
      http:
        paths:
          - path: /febe-rest-f09b7e05-2e20-45d4-9407-7ac6d0cf59ce/
            pathType: Prefix
            backend:
              service:
                name: rest-service-f09b7e05-2e20-45d4-9407-7ac6d0cf59ce
                port:
                  number: 80
