apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-app-28fe4287-5ebc-4d88-849a-3cc27bd070d5
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
  labels:
    app: rest-app-28fe4287-5ebc-4d88-849a-3cc27bd070d5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-app-28fe4287-5ebc-4d88-849a-3cc27bd070d5
  template:
    metadata:
      labels:
        app: rest-app-28fe4287-5ebc-4d88-849a-3cc27bd070d5
    spec:
      containers:
      - name: rest28fe4287-5ebc-4d88-849a-3cc27bd070d5
        image: ravi8881/2e49f282-85d5-4866-af7d-8133a75e6769--bc5fa525-1f32-4c53-bf17-b98dd59ff12e-c0ab55d1-3bd3-4dbb-a1c8-a80818b7e521-rest:6.0.0
        ports:
        - containerPort: 8080
