apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rest-ingress-
  namespace: 85c8a741-63c7-438b-8abe-9fe23efa41e5
  labels:
    app: rest-app-
spec:
  ingressClassName: nginx
  rules:
    - host: 
      http:
        paths:
          - path: /febe-rest-/
            pathType: Prefix
            backend:
              service:
                name: rest-service-
                port:
                  number: 80
