apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rest-ingress-4bd7ef21-deca-430e-81c4-f8ae3f003bb6
  namespace: 85c8a741-63c7-438b-8abe-9fe23efa41e5
  labels:
    app: rest-app-4bd7ef21-deca-430e-81c4-f8ae3f003bb6
spec:
  ingressClassName: nginx
  rules:
    - host: 
      http:
        paths:
          - path: /febe-rest-4bd7ef21-deca-430e-81c4-f8ae3f003bb6/
            pathType: Prefix
            backend:
              service:
                name: rest-service-4bd7ef21-deca-430e-81c4-f8ae3f003bb6
                port:
                  number: 80
