apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-app-98451fb4-15a4-4418-95a4-67d5e5c3d0e1
  namespace: 3219e62e-f28c-4e9a-b62e-77aae69fb44b
  labels:
    app: rest-app-98451fb4-15a4-4418-95a4-67d5e5c3d0e1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-app-98451fb4-15a4-4418-95a4-67d5e5c3d0e1
  template:
    metadata:
      labels:
        app: rest-app-98451fb4-15a4-4418-95a4-67d5e5c3d0e1
    spec:
      containers:
      - name: rest98451fb4-15a4-4418-95a4-67d5e5c3d0e1
        image: ravi8881/3219e62e-f28c-4e9a-b62e-77aae69fb44b-70114ee3-7c51-40a6-af98-bd2ca53150ad-17cd568b-1349-4670-a8ae-53d47334febc-03e60079-6a6b-44c7-905e-495c0bfef98d-rest:3.0.0
        ports:
        - containerPort: 8080
