apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-app-5b331d9f-3592-499f-8dc3-18626338bbf2
  namespace: 3219e62e-f28c-4e9a-b62e-77aae69fb44b
  labels:
    app: rest-app-5b331d9f-3592-499f-8dc3-18626338bbf2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-app-5b331d9f-3592-499f-8dc3-18626338bbf2
  template:
    metadata:
      labels:
        app: rest-app-5b331d9f-3592-499f-8dc3-18626338bbf2
    spec:
      containers:
      - name: rest5b331d9f-3592-499f-8dc3-18626338bbf2
        image: ravi8881/3219e62e-f28c-4e9a-b62e-77aae69fb44b-70114ee3-7c51-40a6-af98-bd2ca53150ad-17cd568b-1349-4670-a8ae-53d47334febc-03e60079-6a6b-44c7-905e-495c0bfef98d-rest:5.0.0
        ports:
        - containerPort: 8080
