apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rest-ingress-0f460a37-725d-4a7a-8070-e49b8461b064
  namespace: 3219e62e-f28c-4e9a-b62e-77aae69fb44b
  labels:
    app: rest-app-0f460a37-725d-4a7a-8070-e49b8461b064
spec:
  ingressClassName: nginx
  rules:
    - host: app-q7vd2v.tpg7m3.us-east-2.febe.k8s
      http:
        paths:
          - path: /febe-rest-0f460a37-725d-4a7a-8070-e49b8461b064/
            pathType: Prefix
            backend:
              service:
                name: rest-service-0f460a37-725d-4a7a-8070-e49b8461b064
                port:
                  number: 80
